Skip disappearing block groups
Between getting a dev extent object and retrieving the associated block
group, the block group might have disappeared (e.g. when this is run
during a balance operation):

Traceback (most recent call last):
  File "./heatmap.py", line 145, in <module>
    main()
  File "./heatmap.py", line 92, in main
    block_group = fs.block_group(dev_extent.vaddr)
  File "/home/knorrie/lib/python/btrfs/ctree.py", line 362, in block_group
    return block_groups[0]
IndexError: list index out of range

In this case, just skip the whole thing instead of crashing.